// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsersMicroservice.DBContexts;

namespace UsersMicroservice.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190528053236_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UsersMicroservice.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos");

                    b.Property<bool>("Estatus");

                    b.Property<DateTime>("FechaIngreso");

                    b.Property<DateTime>("FechaModifica");

                    b.Property<string>("Ingreso");

                    b.Property<string>("Modifica");

                    b.Property<string>("Nombres");

                    b.Property<int>("NumMatricula");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.HasKey("IdUser");

                    b.ToTable("Users");

                    b.HasData(
                        new { IdUser = 1, Apellidos = "Martinez Magdaleno", Estatus = true, FechaIngreso = new DateTime(2019, 5, 27, 23, 32, 36, 7, DateTimeKind.Local), FechaModifica = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Ingreso = "SMARTINEZ", Nombres = "Samuel Martin", NumMatricula = 182948, Sexo = "M" },
                        new { IdUser = 2, Apellidos = "Maldonado Florez", Estatus = true, FechaIngreso = new DateTime(2019, 5, 27, 23, 32, 36, 9, DateTimeKind.Local), FechaModifica = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Ingreso = "SMARTINEZ", Nombres = "Cesar Javier", NumMatricula = 112897, Sexo = "M" },
                        new { IdUser = 3, Apellidos = "Hernandez Rivas", Estatus = true, FechaIngreso = new DateTime(2019, 5, 27, 23, 32, 36, 9, DateTimeKind.Local), FechaModifica = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Ingreso = "SMARTINEZ", Nombres = "Adrian", NumMatricula = 182996, Sexo = "M" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
